export { Home } from "./Home"
export { Contact } from "./Contact"
export { Error } from "./Error"
export { Register } from "./Register"
export { Login } from "./Login"
export { UserDashboard } from "./users/UserDashboard"
export { AdminDashboard } from "./admins/AdminDashboard"
export { UserProfile } from "./users/UserProfile"
export { UserOrders } from "./users/UserOrders"
export { Orders } from "../components/Orders"

